#define WORLD_EDIT_OUTPOST_RADIUS_MAX 25
#define WORLD_EDIT_OUTPOST_SINGLE_POINT_SAFE_PLACEMENT_CAP 300

/datum/world_edit_generator/outpost_radius
	requires_preview_before_apply = TRUE
	var/static/list/valid_factions = list(FACTION_MARINE, FACTION_UA_REBEL, FACTION_UPP, FACTION_CANC, FACTION_WY, FACTION_FREELANCER, FACTION_TWE, FACTION_TWE_REBEL, FACTION_MERCENARY)
	var/static/list/allowed_barricade_types = list(
		/datum/human_ai_defense/barricade/metal,
		/datum/human_ai_defense/barricade/metal/wired,
		/datum/human_ai_defense/barricade/sandbag,
		/datum/human_ai_defense/barricade/plasteel,
		/datum/human_ai_defense/barricade/plasteel/wired,
		/datum/human_ai_defense/barricade/wooden,
	)
	var/static/list/allowed_sentry_types = list(
		/datum/human_ai_defense/defense/sentry/uscm,
		/datum/human_ai_defense/defense/sentry/uscm/shotgun,
		/datum/human_ai_defense/defense/sentry/uscm/dmr,
		/datum/human_ai_defense/defense/sentry/uscm/mini,
		/datum/human_ai_defense/defense/sentry/upp,
		/datum/human_ai_defense/defense/sentry/wy,
	)
	var/static/list/outpost_family_profiles = list(
		"metal_perimeter" = list(
			"label" = "Металлический периметр",
			"description" = "Ровный металлический контур для универсального форпоста.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm,
			"default_sentry_profile" = "entry_guard",
		),
		"wired_metal_perimeter" = list(
			"label" = "Металл с проволокой",
			"description" = "Жесткий металлический контур с проволокой для проходов и горловин.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal/wired,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal/wired,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/shotgun,
			"default_sentry_profile" = "entry_guard",
		),
		"plasteel_bastion" = list(
			"label" = "Пласталевый бастион",
			"description" = "Тяжелый пласталевый контур для удержания ключевой точки.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/plasteel,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/plasteel,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/dmr,
			"default_sentry_profile" = "inner_guard",
		),
		"plasteel_wired_bastion" = list(
			"label" = "Пласталевый бастион с проволокой",
			"description" = "Усиленная пласталевая оболочка с проволокой для жесткого фронтального отказа.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/plasteel/wired,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/plasteel/wired,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/dmr,
			"default_sentry_profile" = "crossfire",
		),
		"sandbag_redoubt" = list(
			"label" = "Редут из мешков",
			"description" = "Дешевый мешочный контур для временного пехотного укрытия.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/sandbag,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/sandbag,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/shotgun,
			"default_sentry_profile" = "light_cover",
		),
		"wooden_screen" = list(
			"label" = "Деревянное прикрытие",
			"description" = "Быстрое деревянное укрытие для импровизированной линии прикрытия.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/wooden,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/wooden,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/mini,
			"default_sentry_profile" = "none",
		),
		"mixed_standard" = list(
			"label" = "Смешанный стандарт",
			"description" = "Сбалансированный смешанный контур из металла, проволоки и мешков.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/metal/wired,
				/datum/human_ai_defense/barricade/sandbag,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm,
			"default_sentry_profile" = "entry_guard",
		),
		"mixed_siege" = list(
			"label" = "Смешанный осадный",
			"description" = "Тяжелая смешанная оболочка с пласталью, проволокой и металлом.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/plasteel,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/plasteel,
				/datum/human_ai_defense/barricade/plasteel/wired,
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/metal/wired,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/dmr,
			"default_sentry_profile" = "crossfire",
		),
		"expedition_light" = list(
			"label" = "Легкий экспедиционный",
			"description" = "Легкий передовой пост для временного удержания и разведывательных остановок.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/sandbag,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm,
			"default_sentry_profile" = "light_cover",
		),
		"assault_screen" = list(
			"label" = "Штурмовой экран",
			"description" = "Рваная передняя линия, чтобы тормозить натиск, а не держать полноценную базу.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/wooden,
			"default_barricade_pattern" = "cycle",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/wooden,
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/metal/wired,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/mini,
			"default_sentry_profile" = "none",
		),
		"choke_wall" = list(
			"label" = "Стена горловины",
			"description" = "Плотная фронтальная стена, которая принуждает к узкому kill lane.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal/wired,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal/wired,
				/datum/human_ai_defense/barricade/plasteel/wired,
				/datum/human_ai_defense/barricade/metal,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/shotgun,
			"default_sentry_profile" = "entry_guard",
		),
		"killbox_wired" = list(
			"label" = "Killbox с проволокой",
			"description" = "Ловушечная оболочка с проволокой, жестким входным deny и огнем внутрь.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/plasteel/wired,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/plasteel/wired,
				/datum/human_ai_defense/barricade/metal/wired,
				/datum/human_ai_defense/barricade/plasteel,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/dmr,
			"default_sentry_profile" = "crossfire",
		),
		"bastion_heavy" = list(
			"label" = "Тяжелый бастион",
			"description" = "Плотный симметричный опорник для важных задач и объектов.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/plasteel,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/plasteel,
				/datum/human_ai_defense/barricade/plasteel/wired,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/dmr,
			"default_sentry_profile" = "inner_guard",
		),
		"mixed_siege_plus" = list(
			"label" = "Усиленный осадный",
			"description" = "Осадный смешанный профиль со слоями тяжелых и легких секций.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/plasteel,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/plasteel,
				/datum/human_ai_defense/barricade/plasteel/wired,
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/metal/wired,
				/datum/human_ai_defense/barricade/sandbag,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/dmr,
			"default_sentry_profile" = "crossfire",
		),
		"sandbag_nest" = list(
			"label" = "Гнездо из мешков",
			"description" = "Пехотный рубеж из мешков для полевых дуг и коротких секторов.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/sandbag,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/sandbag,
				/datum/human_ai_defense/barricade/metal,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/shotgun,
			"default_sentry_profile" = "none",
		),
		"wooden_emergency" = list(
			"label" = "Экстренное деревянное",
			"description" = "Импровизированное аварийное укрытие почти без ощущения капитальности.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/wooden,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/wooden,
				/datum/human_ai_defense/barricade/sandbag,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/mini,
			"default_sentry_profile" = "none",
		),
		"fallback_redoubt" = list(
			"label" = "Редут отхода",
			"description" = "Карман второй линии для отхода, перегруппировки и удержания.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/sandbag,
				/datum/human_ai_defense/barricade/metal/wired,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm,
			"default_sentry_profile" = "inner_guard",
		),
		"lane_fort" = list(
			"label" = "Линейный форт",
			"description" = "Продолговатое укрепление для дорог, тоннелей и длинных улиц.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/metal/wired,
				/datum/human_ai_defense/barricade/plasteel,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm,
			"default_sentry_profile" = "entry_guard",
		),
		"pocket_defense" = list(
			"label" = "Оборонительный карман",
			"description" = "Полузамкнутый карман для удержания ниши, угла или малого узла.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal/wired,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/metal/wired,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/shotgun,
			"default_sentry_profile" = "inner_guard",
		),
		"crossfire_hub" = list(
			"label" = "Узел перекрестного огня",
			"description" = "Многосторонний узел, создающий перекрывающиеся линии огня.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/plasteel,
				/datum/human_ai_defense/barricade/sandbag,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/dmr,
			"default_sentry_profile" = "crossfire",
		),
		"anti_vehicle_stop" = list(
			"label" = "Противотранспортный стоп",
			"description" = "Плотный стоп-слой, чтобы жестко наказывать фронтальный прорыв техники.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/plasteel/wired,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/plasteel,
				/datum/human_ai_defense/barricade/plasteel/wired,
				/datum/human_ai_defense/barricade/metal/wired,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/dmr,
			"default_sentry_profile" = "entry_guard",
		),
		"outrider_camp" = list(
			"label" = "Лагерь аутрайдеров",
			"description" = "Компактный мобильный пост для разведчиков и дозора.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/metal,
			"default_barricade_pattern" = "uniform",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/metal,
				/datum/human_ai_defense/barricade/sandbag,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm/mini,
			"default_sentry_profile" = "none",
		),
		"forward_medical_cover" = list(
			"label" = "Передовое медукрытие",
			"description" = "Защищенная triage-оболочка с более свободным внутренним объемом, чем у killbox.",
			"default_barricade_path" = /datum/human_ai_defense/barricade/sandbag,
			"default_barricade_pattern" = "paired",
			"barricade_mix" = list(
				/datum/human_ai_defense/barricade/sandbag,
				/datum/human_ai_defense/barricade/metal,
			),
			"default_sentry_path" = /datum/human_ai_defense/defense/sentry/uscm,
			"default_sentry_profile" = "light_cover",
		),
	)
	var/static/list/outpost_layout_profiles = list(
		"crossroads" = list(
			"label" = "Крест",
			"description" = "По одному центральному проходу на каждой стороне.",
			"opening_dirs" = list(NORTH, EAST, SOUTH, WEST),
			"guard_dirs" = list(NORTH, EAST, SOUTH, WEST),
			"opening_width" = 1,
		),
		"wide_crossroads" = list(
			"label" = "Широкий крест",
			"description" = "Широкие проходы со всех сторон для максимальной проходимости.",
			"opening_dirs" = list(NORTH, EAST, SOUTH, WEST),
			"guard_dirs" = list(NORTH, EAST, SOUTH, WEST),
			"opening_width" = 3,
		),
		"lane" = list(
			"label" = "Линия",
			"description" = "Проходы вперед и назад, ориентированные по текущему DIR.",
			"opening_dirs" = list("forward", "back"),
			"guard_dirs" = list("forward", "back"),
			"opening_width" = 3,
		),
		"gate" = list(
			"label" = "Ворота",
			"description" = "Один фронтальный проход, привязанный к текущему DIR.",
			"opening_dirs" = list("forward"),
			"guard_dirs" = list("forward"),
			"opening_width" = 3,
		),
		"corner" = list(
			"label" = "Угол",
			"description" = "Проходы вперед и вправо, повернутые по текущему DIR.",
			"opening_dirs" = list("forward", "right"),
			"guard_dirs" = list("forward", "right"),
			"opening_width" = 1,
		),
		"sealed_redoubt" = list(
			"label" = "Запечатанный редут",
			"description" = "Без прямых проходов, только внутренние дуги охвата.",
			"opening_dirs" = list(),
			"guard_dirs" = list(NORTH, EAST, SOUTH, WEST),
			"opening_width" = 1,
		),
		"t_junction" = list(
			"label" = "T-перекресток",
			"description" = "Открыты вперед, влево и вправо, а тыл закрыт.",
			"opening_dirs" = list("forward", "left", "right"),
			"guard_dirs" = list("forward", "left", "right"),
			"opening_width" = 1,
		),
		"three_side_open" = list(
			"label" = "Три стороны открыты",
			"description" = "Открыто вперед, влево и вправо, а тыл заперт.",
			"opening_dirs" = list("forward", "left", "right"),
			"guard_dirs" = list("forward", "left", "right"),
			"opening_width" = 3,
		),
		"three_side_lock" = list(
			"label" = "Три стороны под замком",
			"description" = "Три открытых стороны с дополнительным приоритетом охраны закрытого тыла.",
			"opening_dirs" = list("forward", "left", "right"),
			"guard_dirs" = list("forward", "left", "right", "back"),
			"opening_width" = 1,
		),
		"double_gate" = list(
			"label" = "Двойные ворота",
			"description" = "Парные широкие проходы по оси вперед-назад.",
			"opening_dirs" = list("forward", "back"),
			"guard_dirs" = list("forward", "back"),
			"opening_width" = 3,
		),
		"funnel_front" = list(
			"label" = "Фронтальная воронка",
			"description" = "Широкий фронтальный вход с боковым давлением охраны в проход.",
			"opening_dirs" = list("forward"),
			"guard_dirs" = list("forward", "left", "right"),
			"opening_width" = 3,
		),
		"narrow_funnel" = list(
			"label" = "Узкая воронка",
			"description" = "Тесная фронтальная горловина с минимальной шириной входа.",
			"opening_dirs" = list("forward"),
			"guard_dirs" = list("forward", "left", "right"),
			"opening_width" = 1,
		),
		"broad_funnel" = list(
			"label" = "Широкая воронка",
			"description" = "Очень широкий фронтальный прием с сохранением бокового давления охраны.",
			"opening_dirs" = list("forward"),
			"guard_dirs" = list("forward", "left", "right"),
			"opening_width" = 5,
		),
		"inner_pocket" = list(
			"label" = "Внутренний карман",
			"description" = "Один контролируемый фронтальный вход с более глубоким внутренним охватом.",
			"opening_dirs" = list("forward"),
			"guard_dirs" = list("forward", "left", "right"),
			"opening_width" = 1,
		),
		"fallback_pocket_layout" = list(
			"label" = "Карман отхода",
			"description" = "Фронтально ориентированная схема отхода с боковым карманом выживания.",
			"opening_dirs" = list("forward", "right"),
			"guard_dirs" = list("forward", "right", "back"),
			"opening_width" = 1,
		),
		"split_mouth" = list(
			"label" = "Раздвоенный вход",
			"description" = "Два малых фронтальных входа вместо одного центрального прохода.",
			"opening_dirs" = list("forward"),
			"guard_dirs" = list("forward"),
			"opening_width" = 1,
			"opening_slots_per_dir" = 2,
			"opening_slot_mode" = "split_pair",
		),
		"split_entry_guard" = list(
			"label" = "Раздвоенный вход с охраной",
			"description" = "Раздвоенные фронтальные входы с более широким боковым охватом.",
			"opening_dirs" = list("forward"),
			"guard_dirs" = list("forward", "left", "right"),
			"opening_width" = 1,
			"opening_slots_per_dir" = 2,
			"opening_slot_mode" = "split_pair",
		),
		"corner_wide" = list(
			"label" = "Широкий угол",
			"description" = "Угловая схема с более широкими выходами вперед и вправо.",
			"opening_dirs" = list("forward", "right"),
			"guard_dirs" = list("forward", "right"),
			"opening_width" = 3,
		),
		"lane_narrow" = list(
			"label" = "Узкая линия",
			"description" = "Более плотный контроль линии по оси вперед-назад.",
			"opening_dirs" = list("forward", "back"),
			"guard_dirs" = list("forward", "back"),
			"opening_width" = 1,
		),
		"lane_wide" = list(
			"label" = "Широкая линия",
			"description" = "Широкий линейный контроль по оси вперед-назад.",
			"opening_dirs" = list("forward", "back"),
			"guard_dirs" = list("forward", "back"),
			"opening_width" = 5,
		),
		"bastion_face" = list(
			"label" = "Фасад бастиона",
			"description" = "Один главный боевой проход с боковыми дугами поддержки.",
			"opening_dirs" = list("forward"),
			"guard_dirs" = list("forward", "left", "right"),
			"opening_width" = 1,
		),
		"sealed_shell" = list(
			"label" = "Запечатанная оболочка",
			"description" = "Почти полностью закрытое внешнее кольцо только с внутренней логикой охраны.",
			"opening_dirs" = list(),
			"guard_dirs" = list(NORTH, EAST, SOUTH, WEST),
			"opening_width" = 1,
		),
		"sealed_redoubt_heavy" = list(
			"label" = "Тяжелый запечатанный редут",
			"description" = "Полностью закрытая внешняя оболочка для тяжелых внутренних узлов обороны.",
			"opening_dirs" = list(),
			"guard_dirs" = list(NORTH, EAST, SOUTH, WEST),
			"opening_width" = 1,
		),
	)
	var/static/list/outpost_layout_aliases = list(
		"lane_ns" = "lane",
		"lane_ew" = "lane",
		"north_gate" = "gate",
		"south_gate" = "gate",
		"east_gate" = "gate",
		"west_gate" = "gate",
		"corner_ne" = "corner",
		"corner_se" = "corner",
		"corner_sw" = "corner",
		"corner_nw" = "corner",
		"t_junction_north" = "t_junction",
		"t_junction_south" = "t_junction",
		"t_junction_east" = "t_junction",
		"t_junction_west" = "t_junction",
		"double_gate_ns" = "double_gate",
		"double_gate_ew" = "double_gate",
		"corner_ne_wide" = "corner_wide",
		"corner_se_wide" = "corner_wide",
		"corner_sw_wide" = "corner_wide",
		"corner_nw_wide" = "corner_wide",
		"lane_ns_narrow" = "lane_narrow",
		"lane_ns_wide" = "lane_wide",
		"lane_ew_narrow" = "lane_narrow",
		"lane_ew_wide" = "lane_wide",
		"bastion_face_north" = "bastion_face",
		"bastion_face_south" = "bastion_face",
		"bastion_face_east" = "bastion_face",
		"bastion_face_west" = "bastion_face",
	)

/datum/world_edit_generator/outpost_radius/get_supported_placement_modes()
	return list("single", "repeat")

/datum/world_edit_generator/outpost_radius/get_supported_placement_shapes()
	return GLOB.world_edit_placement_shapes.world_edit_get_supported_shape_ids().Copy()

/datum/world_edit_generator/outpost_radius/supports_placement_direction()
	return TRUE

/datum/world_edit_generator/outpost_radius/get_default_placement_direction()
	return NORTH
