/*
-------------------------
COLONIAL LIBERATION FRONT
-------------------------
*/

/datum/skills/clf
	name = "Инсургент"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_CIVILIAN,
		SKILL_MELEE_WEAPONS = SKILL_MELEE_DEFAULT,
		SKILL_FIREMAN = SKILL_FIREMAN_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_UNTRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_UNTRAINED,
		SKILL_MEDICAL = SKILL_MEDICAL_DEFAULT,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_WEAK,
		SKILL_PILOT = SKILL_PILOT_UNTRAINED,
	)

/datum/skills/clf/combat_engineer
	name = "Инсургент-техник"
	skills = list(
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_ENGI,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
	)

/datum/skills/clf/combat_medic
	name = "Инсургент-медик"
	skills = list(
		SKILL_MEDICAL = SKILL_MEDICAL_MEDIC,
		SKILL_SURGERY = SKILL_SURGERY_TRAINED,
	)

/datum/skills/clf/specialist
	name = "Инсургент-специалист"
	skills = list(
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_NOVICE, //to use c4
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_NOVICE,
	)

/datum/skills/clf/sniper
	name = "Инсургент-снайпер"
	skills = list(
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
	)

/datum/skills/clf/leader
	name = "Инсургент-лидер группы"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_TRAINED,
		SKILL_ENGINEER = SKILL_ENGINEER_TRAINED, // to use C4
		SKILL_CQC = SKILL_CQC_TRAINED,
		SKILL_LEADERSHIP = SKILL_LEAD_EXPERT,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_CONSTRUCTION = SKILL_CONSTRUCTION_TRAINED,
	)

/datum/skills/clf/commander
	name = "Командир ячейки инсургентов"
	skills = list(
		SKILL_FIREARMS = SKILL_FIREARMS_EXPERT,
		SKILL_CQC = SKILL_CQC_SKILLED,
		SKILL_LEADERSHIP = SKILL_LEAD_MASTER,
		SKILL_OVERWATCH = SKILL_OVERWATCH_TRAINED,
		SKILL_FIREMAN = SKILL_FIREMAN_EXPERT,
		SKILL_POWERLOADER = SKILL_POWERLOADER_TRAINED,
		SKILL_VEHICLE = SKILL_VEHICLE_SMALL,
		SKILL_ENDURANCE = SKILL_ENDURANCE_TRAINED,
		SKILL_JTAC = SKILL_JTAC_TRAINED,
		SKILL_SPEC_WEAPONS = SKILL_SPEC_SMARTGUN,
	)
